version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g typescript
      - npm install -g concurrently
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
        - echo Build completed on `date`

artifacts:
  enable-symlinks: true
  files:
    - backend/dist/**/*
    - frontend/dist/**/*
    - package.json
    - package-lock.json
    - backend/package.json
    - backend/package-lock.json
    - frontend/package.json
    - frontend/package-lock.json
    - node_modules/**/*
    - backend/node_modules/**/*
    - frontend/node_modules/**/*
    - frontend/index.html
    - frontend/*.js
    - frontend/vite.config.ts

name: prod-build-$(date +%Y-%m-%d)