version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g typescript
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm prune --production
  post_build:
    commands:
        - echo Build completed on `date`

artifacts:
  files:
    - dist/**/*
    - package.json
    - package-lock.json
    - node_modules/**/*

name: prod-build-$(date +%Y-%m-%d)