name: linter

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest

    env: #Define environment variables for the runtime
      GITHUB_TOKEN: ${{ secrets.GithubAPITokenTaylor }}
      LOG_LEVEL: 0
      LOG_FILE: "logging.txt"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js v18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Lint
        run: npm run lint
